// Frozen approved source matrix; this fixture does not import the runtime catalog.
const MANAGERS = ["admin", "trainer"] as const;
const LEADERS = ["admin", "trainer", "leader"] as const;
const ALL = ["admin", "trainer", "leader", "agent"] as const;
const ADMIN = ["admin"] as const;
const rows = [
  ["GET", "/v1/admin/users", "admin.users", MANAGERS],
  ["PUT", "/v1/admin/users/:id/status", "admin.users", MANAGERS],
  ["PUT", "/v1/admin/users/:id/role", "admin.users", MANAGERS],
  ["DELETE", "/v1/admin/users/:id", "admin.users", MANAGERS],
  ["GET", "/v1/admin/access-groups", "admin.accessGroups", MANAGERS],
  ["POST", "/v1/admin/access-groups", "admin.accessGroups", MANAGERS],
  ["PUT", "/v1/admin/access-groups/:id", "admin.accessGroups", MANAGERS],
  ["GET", "/v1/admin/access-groups/:id/items", "admin.accessGroups", MANAGERS],
  ["POST", "/v1/admin/access-groups/:id/items", "admin.accessGroups", MANAGERS],
  [
    "DELETE",
    "/v1/admin/access-groups/items/:itemId",
    "admin.accessGroups",
    MANAGERS,
  ],
  ["GET", "/v1/admin/access-scope-options", "admin.accessGroups", MANAGERS],
  ["GET", "/v1/admin/leader-requests/pending", "admin.leaderAccess", MANAGERS],
  ["GET", "/v1/admin/leader-requests/approved", "admin.leaderAccess", MANAGERS],
  [
    "POST",
    "/v1/admin/leader-requests/:id/approve",
    "admin.leaderAccess",
    MANAGERS,
  ],
  [
    "POST",
    "/v1/admin/leader-requests/:id/reject",
    "admin.leaderAccess",
    MANAGERS,
  ],
  [
    "POST",
    "/v1/admin/leader-requests/:id/revoke",
    "admin.leaderAccess",
    MANAGERS,
  ],
  [
    "PUT",
    "/v1/admin/leader-requests/:id/groups",
    "admin.leaderAccess",
    MANAGERS,
  ],
  ["POST", "/v1/admin/users/:id/reset-password", "admin.users", MANAGERS],
  ["GET", "/v1/admin/activity-logs", "admin.activityLogs.read", MANAGERS],
  [
    "DELETE",
    "/v1/admin/activity-logs/:id",
    "admin.activityLogs.delete",
    MANAGERS,
  ],
  ["GET", "/v1/ai/models", "ai.models.read", ALL],
  ["POST", "/v1/ai/generate", "ai.generate", MANAGERS],
  ["GET", "/v1/ai/usage", "usage.read", ALL],
  ["GET", "/v1/ai/usage/summary", "usage.read", ALL],
  ["GET", "/v1/ai/monitoring/history", "monitoring.read", LEADERS],
  [
    "GET",
    "/v1/ai/monitoring/history/:module/:id/review",
    "monitoring.read",
    LEADERS,
  ],
  [
    "DELETE",
    "/v1/ai/monitoring/history/:module/:id",
    "monitoring.history.delete",
    MANAGERS,
  ],
  ["GET", "/v1/ai/monitoring/aggregation", "monitoring.read", LEADERS],
  ["GET", "/v1/ai/monitoring/pricing", "monitoring.pricing.read", MANAGERS],
  ["PUT", "/v1/ai/monitoring/pricing", "monitoring.pricing.write", MANAGERS],
  ["GET", "/v1/ai/monitoring/billing", "monitoring.billing.read", MANAGERS],
  ["POST", "/v1/ai/monitoring/billing", "monitoring.billing.write", MANAGERS],
  ["GET", "/v1/ketik/scenarios", "ketik.use", ALL],
  ["GET", "/v1/ketik/consumer-types", "ketik.use", ALL],
  ["POST", "/v1/ketik/generate", "ketik.use", ALL],
  ["GET", "/v1/ketik/settings", "ketik.settings.read", ALL],
  ["PUT", "/v1/ketik/templates", "ketik.templates.shared.write", ADMIN],
  ["PUT", "/v1/ketik/settings", "ketik.settings.write", ALL],
  ["GET", "/v1/ketik/history", "ketik.history.read", ALL],
  ["POST", "/v1/ketik/history", "ketik.history.write", ALL],
  ["DELETE", "/v1/ketik/history", "ketik.history.delete", ALL],
  ["DELETE", "/v1/ketik/history/:id", "ketik.history.delete", ALL],
  ["GET", "/v1/ketik/review/:sessionId", "ketik.review.read", ALL],
  ["POST", "/v1/ketik/review", "ketik.review", MANAGERS],
  ["GET", "/v1/ketik/review/status/:sessionId", "ketik.review.read", ALL],
  ["GET", "/v1/ketik/worker", "ketik.worker.process", MANAGERS],
  ["GET", "/v1/pdkt/history", "pdkt.history.read", ALL],
  ["GET", "/v1/pdkt/history/eval/:id", "pdkt.history.read", ALL],
  ["POST", "/v1/pdkt/history/retry-eval", "pdkt.history.retry", ALL],
  ["DELETE", "/v1/pdkt/history", "pdkt.history.delete", ALL],
  ["DELETE", "/v1/pdkt/history/:id", "pdkt.history.delete", ALL],
  ["GET", "/v1/pdkt/mailbox", "pdkt.mailbox.read", ALL],
  ["GET", "/v1/pdkt/mailbox/:id", "pdkt.mailbox.read", ALL],
  ["POST", "/v1/pdkt/mailbox/batch", "pdkt.mailbox.create", ALL],
  ["DELETE", "/v1/pdkt/mailbox/:id", "pdkt.mailbox.delete", ALL],
  ["POST", "/v1/pdkt/mailbox/batch-delete", "pdkt.mailbox.delete", ALL],
  ["POST", "/v1/pdkt/mailbox/reply", "pdkt.mailbox.reply", ALL],
  ["POST", "/v1/pdkt/mailbox/evaluate", "pdkt.evaluate", LEADERS],
  ["GET", "/v1/pdkt/settings", "pdkt.settings.read", ALL],
  ["POST", "/v1/pdkt/settings", "pdkt.settings.write", ALL],
  ["GET", "/v1/pdkt/scenarios", "pdkt.use", ALL],
  ["GET", "/v1/pdkt/consumer-types", "pdkt.use", ALL],
  ["POST", "/v1/pdkt/generate-identity", "pdkt.use", ALL],
  ["POST", "/v1/pdkt/generate-template", "pdkt.templates.generate", LEADERS],
  ["POST", "/v1/pdkt/session/init", "pdkt.use", ALL],
  ["POST", "/v1/pdkt/session/create", "pdkt.use", ALL],
  ["GET", "/v1/profiler/years", "profiler.read", LEADERS],
  ["POST", "/v1/profiler/years", "profiler.write", MANAGERS],
  ["DELETE", "/v1/profiler/years/:id", "profiler.write", MANAGERS],
  ["GET", "/v1/profiler/folders", "profiler.read", LEADERS],
  ["POST", "/v1/profiler/folders", "profiler.write", MANAGERS],
  ["PUT", "/v1/profiler/folders/:id", "profiler.write", MANAGERS],
  ["DELETE", "/v1/profiler/folders/:id", "profiler.write", MANAGERS],
  ["POST", "/v1/profiler/folders/duplicate", "profiler.write", MANAGERS],
  ["GET", "/v1/profiler/counts", "profiler.read", LEADERS],
  ["GET", "/v1/profiler/peserta", "profiler.read", LEADERS],
  ["GET", "/v1/profiler/peserta/global-pool", "profiler.read", LEADERS],
  ["GET", "/v1/profiler/peserta/upcoming-birthdays", "profiler.read", LEADERS],
  ["GET", "/v1/profiler/peserta/batch/:batchName", "profiler.read", LEADERS],
  [
    "GET",
    "/v1/profiler/peserta/options",
    "simulation.subject.select",
    MANAGERS,
  ],
  ["GET", "/v1/profiler/peserta/:id", "profiler.read", LEADERS],
  ["POST", "/v1/profiler/peserta", "profiler.write", MANAGERS],
  ["PUT", "/v1/profiler/peserta/:id", "profiler.write", MANAGERS],
  ["DELETE", "/v1/profiler/peserta/:id", "profiler.write", MANAGERS],
  ["POST", "/v1/profiler/peserta/bulk", "profiler.write", MANAGERS],
  ["POST", "/v1/profiler/peserta/copy", "profiler.write", MANAGERS],
  ["POST", "/v1/profiler/peserta/move", "profiler.write", MANAGERS],
  ["PUT", "/v1/profiler/peserta/reorder", "profiler.write", MANAGERS],
  ["POST", "/v1/profiler/peserta/bulk-reorder", "profiler.write", MANAGERS],
  ["GET", "/v1/profiler/teams", "profiler.read", LEADERS],
  ["POST", "/v1/profiler/teams", "profiler.write", MANAGERS],
  ["DELETE", "/v1/profiler/teams/:id", "profiler.write", MANAGERS],
  ["GET", "/v1/sidak/periods", "sidak.config.read", LEADERS],
  ["POST", "/v1/sidak/periods", "sidak.write", MANAGERS],
  ["DELETE", "/v1/sidak/periods/:id", "sidak.write", MANAGERS],
  ["GET", "/v1/sidak/resolved-input-config", "sidak.config.read", LEADERS],
  ["GET", "/v1/sidak/indicators", "sidak.config.read", LEADERS],
  ["POST", "/v1/sidak/indicators", "sidak.write", MANAGERS],
  ["GET", "/v1/sidak/folders", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/folders/:folder/agents", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/agents", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/agents/:id/quickview", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/agents/:id", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/dashboard", "sidak.dashboard.read", ALL],
  [
    "POST",
    "/v1/sidak/dashboard/refresh-summary",
    "sidak.summary.refresh",
    MANAGERS,
  ],
  ["POST", "/v1/sidak/dashboard/forecast", "sidak.forecast.generate", LEADERS],
  ["GET", "/v1/sidak/dashboard/available-years", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/dashboard/trend", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/service-weights", "sidak.config.read", LEADERS],
  ["PUT", "/v1/sidak/service-weights/:serviceType", "sidak.write", MANAGERS],
  ["GET", "/v1/sidak/ranking", "sidak.read", LEADERS],
  ["POST", "/v1/sidak/forecast/agents", "sidak.forecast.generate", LEADERS],
  ["GET", "/v1/sidak/heatmap", "sidak.read", LEADERS],
  ["GET", "/v1/sidak/jadwal-shifting", "sidak.schedule.read", MANAGERS],
  ["GET", "/v1/sidak/jadwal-shifting/month", "sidak.schedule.read", MANAGERS],
  ["POST", "/v1/sidak/reports/data", "sidak.reports.generate", LEADERS],
  ["POST", "/v1/sidak/reports/ai/generate", "sidak.reports.generate", LEADERS],
  [
    "POST",
    "/v1/sidak/reports/ai/export-docx",
    "sidak.reports.generate",
    LEADERS,
  ],
  [
    "POST",
    "/v1/sidak/reports/ai/export-html",
    "sidak.reports.generate",
    LEADERS,
  ],
  [
    "POST",
    "/v1/sidak/reports/ai/chart-data",
    "sidak.reports.generate",
    LEADERS,
  ],
  ["POST", "/v1/sidak/reports/ai/save", "sidak.reports.generate", LEADERS],
  ["GET", "/v1/sidak/reports/archives", "sidak.archives.read", ALL],
  ["GET", "/v1/sidak/reports/archives/:id", "sidak.archives.read", ALL],
  ["DELETE", "/v1/sidak/reports/archives/:id", "sidak.archives.delete", ALL],
  [
    "POST",
    "/v1/sidak/reports/ai/export-pdf",
    "sidak.reports.generate",
    LEADERS,
  ],
  ["GET", "/v1/sidak/rule-versions", "sidak.config.read", LEADERS],
  ["GET", "/v1/sidak/rule-versions/meta", "sidak.config.read", LEADERS],
  ["POST", "/v1/sidak/rule-versions", "sidak.write", MANAGERS],
  ["PUT", "/v1/sidak/rule-versions/:id", "sidak.write", MANAGERS],
  ["DELETE", "/v1/sidak/rule-versions/:id", "sidak.write", MANAGERS],
  ["POST", "/v1/sidak/rule-versions/:id/publish", "sidak.write", MANAGERS],
  ["POST", "/v1/sidak/rule-versions/:id/supersede", "sidak.write", MANAGERS],
  [
    "GET",
    "/v1/sidak/rule-versions/:id/indicators",
    "sidak.config.read",
    LEADERS,
  ],
  ["POST", "/v1/sidak/rule-versions/:id/indicators", "sidak.write", MANAGERS],
  [
    "DELETE",
    "/v1/sidak/rule-versions/:versionId/indicators/:indicatorId",
    "sidak.write",
    MANAGERS,
  ],
  [
    "PUT",
    "/v1/sidak/rule-versions/:versionId/indicators/:indicatorId",
    "sidak.write",
    MANAGERS,
  ],
  ["GET", "/v1/sidak/agents/:id/simulations", "sidak.read", LEADERS],
  [
    "GET",
    "/v1/sidak/agents/:id/simulations/:module/:historyId",
    "sidak.read",
    LEADERS,
  ],
  ["GET", "/v1/sidak/temuan", "sidak.read", LEADERS],
  ["POST", "/v1/sidak/temuan/batch", "sidak.write", MANAGERS],
  ["POST", "/v1/sidak/temuan/batch/preview", "sidak.write", MANAGERS],
  ["PUT", "/v1/sidak/temuan/:id", "sidak.write", MANAGERS],
  ["DELETE", "/v1/sidak/temuan/:id", "sidak.write", MANAGERS],
  ["POST", "/v1/sidak/temuan/perfect-session", "sidak.write", MANAGERS],
  ["GET", "/v1/telefun/annotations/:id", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/annotations/:id", "telefun.use", MANAGERS],
  ["DELETE", "/v1/telefun/annotations/:annotationId", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/annotations/generate/:id", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/capabilities", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/finalize-recording", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/recording/:id", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/score/:id", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/coaching-summary/:id", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/remux-recording/:sessionId", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/sessions", "telefun.use", MANAGERS],
  ["POST", "/v1/telefun/sessions", "telefun.use", MANAGERS],
  ["PATCH", "/v1/telefun/sessions/:id", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/history/:id", "telefun.use", MANAGERS],
  ["DELETE", "/v1/telefun/history/:id", "telefun.use", MANAGERS],
  ["DELETE", "/v1/telefun/history", "telefun.use", MANAGERS],
  ["GET", "/v1/telefun/settings", "telefun.use", MANAGERS],
  ["PUT", "/v1/telefun/settings", "telefun.use", MANAGERS],
] as const;
export const ACCESS_MATRIX = rows.map(([method, path, capability, roles]) => ({
  method,
  path,
  capability,
  roles,
}));
