-- Telefun scoring claim fencing + longer lease.
-- Additive: the legacy RPC signatures remain during the rollout overlap;
-- new API/worker code uses the tokenized signatures below.

ALTER TABLE public.telefun_history
  ADD COLUMN IF NOT EXISTS scoring_claim_token_hash TEXT,
  ADD COLUMN IF NOT EXISTS scoring_claim_owner TEXT;

CREATE INDEX IF NOT EXISTS idx_telefun_scoring_claim_token_hash
  ON public.telefun_history(scoring_claim_token_hash)
  WHERE scoring_status = 'processing';

-- Tokenized claim. The token hash is generated by the trusted API/worker and
-- is never returned to clients or stored in plaintext.
CREATE OR REPLACE FUNCTION public.claim_telefun_scoring(
  p_session_id UUID,
  p_claim_timeout_seconds INT,
  p_claim_token_hash TEXT,
  p_claim_owner TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_current_status TEXT;
  v_claimed_at TIMESTAMPTZ;
  v_next_attempt TIMESTAMPTZ;
  v_transport TEXT;
  v_session_status TEXT;
  v_scoring_ready_at TIMESTAMPTZ;
  v_agent_path TEXT;
  v_user_id UUID;
  v_now TIMESTAMPTZ := now();
BEGIN
  IF p_claim_timeout_seconds IS NULL OR p_claim_timeout_seconds < 300
     OR p_claim_token_hash IS NULL OR p_claim_token_hash = ''
     OR p_claim_owner IS NULL OR p_claim_owner = '' THEN
    RETURN FALSE;
  END IF;

  SELECT h.scoring_status, h.scoring_claimed_at, h.scoring_next_attempt_at,
         h.telefun_transport, h.status, h.scoring_ready_at,
         h.agent_recording_path, h.user_id
  INTO v_current_status, v_claimed_at, v_next_attempt,
       v_transport, v_session_status, v_scoring_ready_at,
       v_agent_path, v_user_id
  FROM public.telefun_history h
  WHERE h.id = p_session_id
  FOR UPDATE;

  IF v_current_status IS NULL THEN RETURN FALSE; END IF;
  IF v_current_status = 'completed' THEN RETURN FALSE; END IF;
  -- Phase 4 durable-lifecycle guard: WebRTC rows are claimable only when the
  -- session completed with an owned seekable agent path and scoring is ready.
  IF v_transport = 'openai-webrtc' AND (
    v_session_status <> 'completed'
    OR v_scoring_ready_at IS NULL
    OR v_agent_path IS NULL
    OR v_agent_path !~ ('^' || v_user_id::text || '/' || p_session_id::text || '/agent_only\.seekable\.webm$')
  ) THEN RETURN FALSE; END IF;

  IF v_current_status = 'processing' AND v_claimed_at IS NOT NULL
     AND (v_now - v_claimed_at) < make_interval(secs => p_claim_timeout_seconds) THEN
    RETURN FALSE;
  END IF;

  IF v_current_status IN ('pending', 'failed')
     AND v_next_attempt IS NOT NULL AND v_next_attempt > v_now THEN
    RETURN FALSE;
  END IF;

  UPDATE public.telefun_history
  SET scoring_status = 'processing',
      scoring_claimed_at = v_now,
      scoring_claim_token_hash = p_claim_token_hash,
      scoring_claim_owner = p_claim_owner,
      scoring_attempt_count = COALESCE(scoring_attempt_count, 0) + 1,
      scoring_last_error = NULL,
      scoring_next_attempt_at = NULL
  WHERE id = p_session_id;

  RETURN FOUND;
END;
$$;

-- Compatibility signature for the old Railway worker during rollout. It keeps
-- the two-argument call unambiguous and uses the longer lease. Legacy writes
-- below are allowed only while the claim has no fencing token; once a new
-- tokenized claim wins, stale legacy completion/failure cannot overwrite it.
CREATE OR REPLACE FUNCTION public.claim_telefun_scoring(
  p_session_id UUID,
  p_claim_timeout_seconds INT DEFAULT 300
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_current_status TEXT;
  v_claimed_at TIMESTAMPTZ;
  v_next_attempt TIMESTAMPTZ;
  v_transport TEXT;
  v_session_status TEXT;
  v_scoring_ready_at TIMESTAMPTZ;
  v_agent_path TEXT;
  v_user_id UUID;
  v_effective_timeout INT;
  v_now TIMESTAMPTZ := now();
BEGIN
  v_effective_timeout := GREATEST(COALESCE(p_claim_timeout_seconds, 300), 300);

  SELECT h.scoring_status, h.scoring_claimed_at, h.scoring_next_attempt_at,
         h.telefun_transport, h.status, h.scoring_ready_at,
         h.agent_recording_path, h.user_id
  INTO v_current_status, v_claimed_at, v_next_attempt,
       v_transport, v_session_status, v_scoring_ready_at,
       v_agent_path, v_user_id
  FROM public.telefun_history h
  WHERE h.id = p_session_id
  FOR UPDATE;

  IF v_current_status IS NULL THEN RETURN FALSE; END IF;
  IF v_current_status = 'completed' THEN RETURN FALSE; END IF;
  -- Phase 4 durable-lifecycle guard (same as tokenized claim): WebRTC rows
  -- are claimable only when the session completed with an owned seekable
  -- agent path and scoring is ready.
  IF v_transport = 'openai-webrtc' AND (
    v_session_status <> 'completed'
    OR v_scoring_ready_at IS NULL
    OR v_agent_path IS NULL
    OR v_agent_path !~ ('^' || v_user_id::text || '/' || p_session_id::text || '/agent_only\.seekable\.webm$')
  ) THEN RETURN FALSE; END IF;
  IF v_current_status = 'processing' AND v_claimed_at IS NOT NULL
     AND (v_now - v_claimed_at) < make_interval(secs => v_effective_timeout) THEN
    RETURN FALSE;
  END IF;
  IF v_current_status IN ('pending', 'failed')
     AND v_next_attempt IS NOT NULL AND v_next_attempt > v_now THEN
    RETURN FALSE;
  END IF;

  UPDATE public.telefun_history
  SET scoring_status = 'processing',
      scoring_claimed_at = v_now,
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = 'legacy-scoring-worker',
      scoring_attempt_count = COALESCE(scoring_attempt_count, 0) + 1,
      scoring_last_error = NULL,
      scoring_next_attempt_at = NULL
  WHERE id = p_session_id;

  RETURN FOUND;
END;
$$;

-- Legacy completion/failure/reschedule remain callable only for an un-tokenized
-- claim. New code always uses the tokenized overloads above. The Phase 4
-- durable-lifecycle row lock + readiness guards are preserved verbatim.
CREATE OR REPLACE FUNCTION public.complete_telefun_scoring(
  p_session_id UUID,
  p_score NUMERIC,
  p_voice_assessment JSONB DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_id UUID;
  v_user_id UUID;
  v_status TEXT;
  v_transport TEXT;
  v_recording_status TEXT;
  v_recording_error TEXT;
  v_scoring_status TEXT;
  v_scoring_ready_at TIMESTAMPTZ;
  v_agent_recording_path TEXT;
  v_claim_token_hash TEXT;
BEGIN
  SELECT h.id,
         h.user_id,
         h.status,
         h.telefun_transport,
         h.recording_status,
         h.recording_error,
         h.scoring_status,
         h.scoring_ready_at,
         h.agent_recording_path,
         h.scoring_claim_token_hash
  INTO v_id,
       v_user_id,
       v_status,
       v_transport,
       v_recording_status,
       v_recording_error,
       v_scoring_status,
       v_scoring_ready_at,
       v_agent_recording_path,
       v_claim_token_hash
  FROM public.telefun_history h
  WHERE h.id = p_session_id
  FOR UPDATE;

  IF NOT FOUND OR v_id IS NULL OR v_scoring_status <> 'processing' THEN
    RETURN FALSE;
  END IF;

  -- Legacy path must not clobber a tokenized claim.
  IF v_claim_token_hash IS NOT NULL THEN
    RETURN FALSE;
  END IF;

  IF v_transport IS DISTINCT FROM 'openai-webrtc' THEN
    -- Gemini and legacy OpenAI WebSocket rows retain the prior raw-agent-path
    -- completion behavior; the lock only makes the existing claim deterministic.
    NULL;
  ELSIF v_status <> 'completed'
     OR v_recording_status IS NULL
     OR v_recording_status NOT IN ('partial', 'ready')
     OR v_recording_status = 'failed'
     OR v_recording_error IS NOT NULL
     OR v_scoring_ready_at IS NULL
     OR v_agent_recording_path IS DISTINCT FROM
       v_user_id::text || '/' || p_session_id::text || '/agent_only.seekable.webm' THEN
    RETURN FALSE;
  END IF;

  UPDATE public.telefun_history
  SET scoring_status = 'completed',
      scoring_completed_at = now(),
      score = p_score,
      voice_assessment = COALESCE(p_voice_assessment, voice_assessment),
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND scoring_claim_token_hash IS NULL;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_telefun_scoring(
  p_session_id UUID,
  p_error TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.telefun_history
  SET scoring_status = 'failed',
      scoring_last_error = p_error,
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND scoring_claim_token_hash IS NULL;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.reschedule_telefun_scoring(
  p_session_id UUID,
  p_error TEXT,
  p_next_attempt_at TIMESTAMPTZ
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.telefun_history
  SET scoring_status = 'failed',
      scoring_last_error = p_error,
      scoring_next_attempt_at = p_next_attempt_at,
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND scoring_claim_token_hash IS NULL;
  RETURN FOUND;
END;
$$;

-- Tokenized completion follows the compatibility definitions. The Phase 4
-- durable-lifecycle row lock + readiness guards are preserved verbatim; the
-- claim token match is enforced on top so a stale worker cannot overwrite
-- the current claim.
CREATE OR REPLACE FUNCTION public.complete_telefun_scoring(
  p_session_id UUID,
  p_score NUMERIC,
  p_voice_assessment JSONB,
  p_claim_token_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_id UUID;
  v_user_id UUID;
  v_status TEXT;
  v_transport TEXT;
  v_recording_status TEXT;
  v_recording_error TEXT;
  v_scoring_status TEXT;
  v_scoring_ready_at TIMESTAMPTZ;
  v_agent_recording_path TEXT;
  v_claim_token_hash TEXT;
BEGIN
  IF p_claim_token_hash IS NULL OR p_claim_token_hash = '' THEN
    RETURN FALSE;
  END IF;

  SELECT h.id,
         h.user_id,
         h.status,
         h.telefun_transport,
         h.recording_status,
         h.recording_error,
         h.scoring_status,
         h.scoring_ready_at,
         h.agent_recording_path,
         h.scoring_claim_token_hash
  INTO v_id,
       v_user_id,
       v_status,
       v_transport,
       v_recording_status,
       v_recording_error,
       v_scoring_status,
       v_scoring_ready_at,
       v_agent_recording_path,
       v_claim_token_hash
  FROM public.telefun_history h
  WHERE h.id = p_session_id
  FOR UPDATE;

  IF NOT FOUND OR v_id IS NULL OR v_scoring_status <> 'processing' THEN
    RETURN FALSE;
  END IF;

  -- Fencing: only the current claim owner may complete.
  IF v_claim_token_hash IS DISTINCT FROM p_claim_token_hash THEN
    RETURN FALSE;
  END IF;

  IF v_transport IS DISTINCT FROM 'openai-webrtc' THEN
    -- Gemini and legacy OpenAI WebSocket rows retain the prior raw-agent-path
    -- completion behavior; the lock only makes the existing claim deterministic.
    NULL;
  ELSIF v_status <> 'completed'
     OR v_recording_status IS NULL
     OR v_recording_status NOT IN ('partial', 'ready')
     OR v_recording_status = 'failed'
     OR v_recording_error IS NOT NULL
     OR v_scoring_ready_at IS NULL
     OR v_agent_recording_path IS DISTINCT FROM
       v_user_id::text || '/' || p_session_id::text || '/agent_only.seekable.webm' THEN
    RETURN FALSE;
  END IF;

  UPDATE public.telefun_history
  SET scoring_status = 'completed',
      scoring_completed_at = now(),
      score = p_score,
      voice_assessment = COALESCE(p_voice_assessment, voice_assessment),
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND scoring_claim_token_hash IS NOT DISTINCT FROM p_claim_token_hash;

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_telefun_scoring(
  p_session_id UUID,
  p_error TEXT,
  p_claim_token_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.telefun_history
  SET scoring_status = 'failed',
      scoring_last_error = p_error,
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND p_claim_token_hash IS NOT NULL
    AND scoring_claim_token_hash IS NOT DISTINCT FROM p_claim_token_hash;

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.reschedule_telefun_scoring(
  p_session_id UUID,
  p_error TEXT,
  p_next_attempt_at TIMESTAMPTZ,
  p_claim_token_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.telefun_history
  SET scoring_status = 'failed',
      scoring_last_error = p_error,
      scoring_next_attempt_at = p_next_attempt_at,
      scoring_claim_token_hash = NULL,
      scoring_claim_owner = NULL
  WHERE id = p_session_id
    AND scoring_status = 'processing'
    AND p_claim_token_hash IS NOT NULL
    AND scoring_claim_token_hash IS NOT DISTINCT FROM p_claim_token_hash;

  RETURN FOUND;
END;
$$;

-- New signatures are service-role-only. Legacy signatures stay available until
-- the old Railway service has been disabled and a later cleanup is approved.
REVOKE ALL ON FUNCTION public.claim_telefun_scoring(UUID, INT, TEXT, TEXT)
  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_telefun_scoring(UUID, NUMERIC, JSONB, TEXT)
  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.fail_telefun_scoring(UUID, TEXT, TEXT)
  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.reschedule_telefun_scoring(UUID, TEXT, TIMESTAMPTZ, TEXT)
  FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_telefun_scoring(UUID, INT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_telefun_scoring(UUID, NUMERIC, JSONB, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_telefun_scoring(UUID, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.reschedule_telefun_scoring(UUID, TEXT, TIMESTAMPTZ, TEXT) TO service_role;

NOTIFY pgrst, 'reload schema';
