import type { KetikIdentity, KetikIdentitySettings } from "@trainers/types";

const DUMMY_NAMES = [
  "Budi Santoso",
  "Siti Aminah",
  "Agus Setiawan",
  "Dewi Lestari",
  "Rina Wati",
  "Eko Prasetyo",
  "Hendra Wijaya",
  "Nurul Hidayah",
  "Bambang Pamungkas",
  "Lina Marlina",
  "Dedi Supriyadi",
  "Sri Wahyuni",
  "Rudi Hartono",
  "Ratna Sari",
  "Joko Widodo",
  "Mega Ayuningtyas",
  "Andi Pratama",
  "Fitri Handayani",
  "Rudi Hermawan",
  "Dian Permana",
  "Lukman Hakim",
  "Ayu Kartika",
  "Fajar Nugroho",
  "Yanti Susanti",
  "Iwan Saputra",
  "Maya Putri",
  "Reza Rahadian",
  "Indah Permatasari",
  "Slamet Riyadi",
  "Tuti Alawiyah",
  "Farhan Maulana",
  "Nabila Zahra",
  "Gilang Ramadhan",
  "Citra Kirana",
  "Bayu Anggara",
  "Wulan Dari",
  "Teuku Fariz",
  "Cut Marlia",
  "I Made Wirata",
  "Ni Luh Ayu",
  "Ujang Komarudin",
  "Eneng Suryani",
  "La Ode Haris",
  "Wa Ode Sitti",
  "Johan Panjaitan",
  "Boruk Sihombing",
  "Daeng Makkawaru",
  "Andi Tenri",
  "Yohanes Korwa",
  "Maria Matulessy",
];
const DUMMY_CITIES = [
  "Jakarta Selatan",
  "Jakarta Pusat",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Utara",
  "Kota Bogor",
  "Kota Depok",
  "Kota Bekasi",
  "Kota Tangerang",
  "Kota Tangerang Selatan",
  "Bandung",
  "Surabaya",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Yogyakarta",
  "Malang",
  "Denpasar",
  "Balikpapan",
  "Samarinda",
  "Banjarmasin",
  "Pontianak",
  "Manado",
  "Padang",
  "Pekanbaru",
  "Bandar Lampung",
  "Batam",
  "Cirebon",
  "Solo",
  "Kediri",
  "Jember",
  "Mataram",
  "Kupang",
  "Ambon",
  "Jayapura",
  "Sorong",
  "Banda Aceh",
  "Bengkulu",
  "Jambi",
  "Cilegon",
  "Serang",
  "Purwokerto",
  "Magelang",
  "Palu",
  "Kendari",
  "Gorontalo",
  "Ternate",
  "Mamuju",
];
const PHONE_PREFIXES = [
  "0812",
  "0813",
  "0821",
  "0852",
  "0811",
  "0815",
  "0817",
  "0818",
  "0819",
  "0822",
  "0823",
  "0851",
  "0853",
  "0856",
  "0857",
  "0858",
  "0895",
  "0896",
];

export function resolveKetikSessionIdentity(
  settings: KetikIdentitySettings,
  pickIndex = Math.floor(Math.random() * 1000000),
): KetikIdentity {
  const name =
    settings.displayName || DUMMY_NAMES[Math.abs(pickIndex) % DUMMY_NAMES.length];
  const city =
    settings.city || DUMMY_CITIES[Math.abs(pickIndex) % DUMMY_CITIES.length];
  const prefix =
    PHONE_PREFIXES[Math.abs(pickIndex) % PHONE_PREFIXES.length];
  const phone =
    settings.phoneNumber ||
    `${prefix}${String(Math.abs(pickIndex)).padStart(8, "0").slice(-8)}`;

  return {
    name,
    city,
    phone,
    signatureName: settings.signatureName,
  };
}
